### ISSUE TITLE
Ugly fail when requesting bar chart if no data in db

### ISSUE THREAD

**Issue by sfsinger19103** [ElectionDataAnalysis/electiondata#232]
```import election_data_analysis as ea
an = ea.Analyzer()
b = an.bar("2018 General","Georgia","congressional")
```
called on a database without any Georgia results yielded:

```Connected to pydev debugger (build 202.7660.27)
Traceback (most recent call last):
  File "/Users/singer3/PycharmProjects/election_data_analysis/venv/lib/python3.8/site-packages/pandas/core/generic.py", line 5143, in __setattr__
    return object.__setattr__(self, name, value)
  File "pandas/_libs/properties.pyx", line 66, in pandas._libs.properties.AxisProperty.__set__
  File "/Users/singer3/PycharmProjects/election_data_analysis/venv/lib/python3.8/site-packages/pandas/core/generic.py", line 564, in _set_axis
    self._mgr.set_axis(axis, labels)
  File "/Users/singer3/PycharmProjects/election_data_analysis/venv/lib/python3.8/site-packages/pandas/core/internals/managers.py", line 226, in set_axis
    raise ValueError(
ValueError: Length mismatch: Expected axis has 0 elements, new values have 20 elements
python-BaseException
```

**Comment by sfsinger19103** [comment]
fixed
